import os
import re
import unicodedata
from collections import Counter
from typing import Any
from urllib.parse import quote, urlparse

from openai import OpenAI


MODELO_BUSQUEDA = "gpt-5.6-luna"
MAXIMO_RESULTADOS = 8
MAXIMO_CONSULTAS = 8
MAXIMO_LLAMADAS_WEB = 4
MAXIMO_RESULTADOS_POR_BUSQUEDA = 10
VARIABLE_MODO = "BUSQUEDA_IMAGENES_MODO"
MODO_PRUEBA = "prueba"
MODO_REAL = "real"

PALABRAS_VACIAS = {
    "actual",
    "actuales",
    "archivo",
    "archivos",
    "ano",
    "anos",
    "buscar",
    "busca",
    "buscando",
    "caption",
    "como",
    "con",
    "de",
    "del",
    "desde",
    "documental",
    "durante",
    "el",
    "en",
    "epoca",
    "foto",
    "fotos",
    "fotografia",
    "fotografias",
    "historica",
    "historicas",
    "historico",
    "historicos",
    "imagen",
    "imagenes",
    "la",
    "las",
    "los",
    "mostrar",
    "muestra",
    "para",
    "por",
    "que",
    "real",
    "reales",
    "sobre",
    "una",
    "uno",
    "ver",
    "vista",
    "with",
    "from",
    "image",
    "images",
    "photo",
    "photograph",
    "photography",
    "realistic",
    "showing",
    "the",
}

PALABRAS_GENERICAS_IDENTIDAD = PALABRAS_VACIAS | {
    "abierta",
    "abierto",
    "actividad",
    "ambiente",
    "calle",
    "ciudad",
    "concierto",
    "entrada",
    "escena",
    "exterior",
    "fachada",
    "grupo",
    "interior",
    "lugar",
    "noche",
    "personas",
    "publico",
    "sala",
}

INDICIOS_OBJETIVO_CONTEXTUAL = {
    "ambiente",
    "apariencia",
    "audience",
    "calle",
    "calles",
    "clothing",
    "colores",
    "crowd",
    "daily",
    "escena",
    "estetica",
    "estilo",
    "fashion",
    "gente",
    "hairstyle",
    "hairstyles",
    "joven",
    "jovenes",
    "look",
    "looks",
    "maquillaje",
    "moda",
    "multitud",
    "outfit",
    "outfits",
    "peinado",
    "peinados",
    "people",
    "personas",
    "publico",
    "punk",
    "punks",
    "ropa",
    "street",
    "streets",
    "style",
    "tribu",
    "tribus",
    "vestimenta",
    "vestuario",
    "vida",
    "young",
}

INDICIOS_SUJETO_EXACTO = {
    "actor",
    "actriz",
    "avion",
    "banda",
    "bar",
    "barco",
    "cantante",
    "castillo",
    "club",
    "cuadro",
    "director",
    "discoteca",
    "edificio",
    "escritor",
    "escritora",
    "estacion",
    "fotografa",
    "fotografo",
    "grupo",
    "hotel",
    "iglesia",
    "mecanismo",
    "museo",
    "obra",
    "objeto",
    "palacio",
    "persona",
    "revista",
    "sala",
    "teatro",
    "tren",
    "vehiculo",
}

INDICIOS_NO_DOCUMENTALES = {
    "actor portraying",
    "actress portraying",
    "ai generated",
    "arte conceptual",
    "concept art",
    "dibujo",
    "fictional scene",
    "generada por ia",
    "generated by ai",
    "ilustracion",
    "illustration",
    "painting",
    "pintura",
    "recreacion",
    "reenactment",
    "representacion artistica",
    "stock illustration",
}

DOMINIOS_DOCUMENTALES = {
    "archive.org",
    "bbc.co.uk",
    "bne.es",
    "britishmuseum.org",
    "europeana.eu",
    "getty.edu",
    "loc.gov",
    "moma.org",
    "museodelprado.es",
    "nationalarchives.gov.uk",
    "si.edu",
    "wikimedia.org",
    "wikipedia.org",
}


def convertir_a_diccionario(valor: Any) -> dict:
    if isinstance(valor, dict):
        return valor

    if hasattr(valor, "model_dump"):
        return valor.model_dump()

    return {}


def texto_seguro(valor: Any) -> str:
    if valor is None:
        return ""

    texto = str(valor).strip()

    if texto.casefold() in {"none", "null", "undefined"}:
        return ""

    return texto


def normalizar_texto(texto: str) -> str:
    texto_normalizado = unicodedata.normalize(
        "NFKD",
        texto_seguro(texto),
    )

    return texto_normalizado.encode(
        "ascii",
        "ignore",
    ).decode("ascii").lower()


def limpiar_consultas(busquedas: list[str]) -> list[str]:
    consultas = []
    consultas_vistas = set()

    for busqueda in busquedas:
        consulta = texto_seguro(busqueda)
        clave = normalizar_texto(consulta)
        clave = re.sub(r"\s+", " ", clave).strip()

        if not consulta or not clave or clave in consultas_vistas:
            continue

        consultas_vistas.add(clave)
        consultas.append(consulta)

        if len(consultas) >= MAXIMO_CONSULTAS:
            break

    return consultas


def obtener_modo_busqueda() -> str:
    modo = os.getenv(
        VARIABLE_MODO,
        MODO_PRUEBA,
    ).strip().casefold()

    if modo not in {MODO_PRUEBA, MODO_REAL}:
        raise ValueError(
            f"{VARIABLE_MODO} debe valer "
            f"'{MODO_PRUEBA}' o '{MODO_REAL}'."
        )

    return modo


def obtener_cliente() -> OpenAI:
    api_key = os.getenv("OPENAI_API_KEY", "").strip()

    if not api_key:
        raise ValueError(
            "Falta OPENAI_API_KEY para realizar una búsqueda real."
        )

    return OpenAI(
        api_key=api_key,
        max_retries=0,
        timeout=60.0,
    )


def crear_imagen_prueba(consulta: str) -> str:
    texto = normalizar_texto(consulta)[:80]
    texto = re.sub(r"[^a-z0-9 ]+", " ", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    texto = texto or "consulta sin texto"

    svg = f"""
<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350">
  <rect width="1080" height="1350" fill="#111827"/>
  <rect x="70" y="70" width="940" height="1210" rx="36"
        fill="#1f2937" stroke="#f5c542" stroke-width="8"/>
  <text x="540" y="520" text-anchor="middle"
        fill="#f5c542" font-family="Arial" font-size="72"
        font-weight="700">MODO PRUEBA</text>
  <text x="540" y="630" text-anchor="middle"
        fill="#ffffff" font-family="Arial" font-size="42">
        0 llamadas API · 0 coste
  </text>
  <text x="540" y="760" text-anchor="middle"
        fill="#d1d5db" font-family="Arial" font-size="30">
        {texto}
  </text>
</svg>
""".strip()

    return "data:image/svg+xml;charset=utf-8," + quote(svg)


def crear_resultado_prueba(consulta: str) -> list[dict]:
    imagen_prueba = crear_imagen_prueba(consulta)

    return [
        {
            "imagen_url": imagen_prueba,
            "miniatura_url": imagen_prueba,
            "fuente_url": "https://example.com/prueba-sin-coste",
            "fuente_nombre": "example.com",
            "titulo": "Simulación sin coste",
            "autor": "",
            "descripcion": (
                "SIMULACIÓN SIN COSTE. La pantalla, el guardado y la "
                "reapertura funcionan. No es una fotografía real y no "
                "debe seleccionarse como imagen definitiva."
            ),
        }
    ]


def crear_prompt_busqueda(
    consultas: list[str],
    max_resultados: int,
) -> str:
    lista_consultas = "\n".join(
        f"{indice}. {consulta}"
        for indice, consulta in enumerate(consultas, start=1)
    )

    return f"""
Localiza fotografías reales y verificables para un Reel documental.
Las indicaciones siguientes son RUTAS DE BÚSQUEDA ALTERNATIVAS para
resolver una misma escena. Pueden mencionar sujetos distintos y no deben
forzarse a compartir una única identidad:

{lista_consultas}

PLAN DE BÚSQUEDA OBLIGATORIO:
1. Evalúa cada ruta por separado y clasifícala internamente como:
   A) SUJETO IDENTIFICABLE: persona, grupo, organización, lugar, edificio,
      objeto, publicación o acontecimiento con nombre propio concreto.
   B) CONTEXTO DOCUMENTAL: moda, estética, público, ambiente, calles,
      vida cotidiana, escena colectiva o participantes anónimos.
2. En una ruta de tipo A, conserva el nombre propio exacto y exige que la
   fuente permita comprobarlo. No lo sustituyas por otro sujeto relacionado.
3. En una ruta de tipo B, conserva el movimiento, lugar y época pedidos,
   junto con los rasgos visuales esenciales. No inventes un sujeto exacto
   cuando la petición busca una estética o una escena colectiva.
4. Haz entre 3 y {MAXIMO_LLAMADAS_WEB} búsquedas web distintas cuando
   sea necesario. Todo debe ocurrir dentro de esta única respuesta.
5. Mantén intactos los nombres propios, apellidos, siglas, fechas y
   denominaciones exactas en todas las búsquedas.
6. No mezcles en una sola consulta nombres propios pertenecientes a rutas
   alternativas diferentes. Busca cada alternativa de forma independiente.
7. Combina las estrategias adecuadas a cada ruta:
   - tipo A: nombre exacto entre comillas + fotografía, encuadre, lugar o época;
   - tipo B: movimiento o contexto + lugar + época + rasgo visual solicitado;
   - usa inglés solo para palabras descriptivas y no traduzcas nombres propios;
   - archivos, museos, bibliotecas, hemerotecas y medios fiables.

REGLAS DOCUMENTALES OBLIGATORIAS:
- Solicita suficientes candidatos y devuelve como máximo
  {max_resultados} fotografías válidas tras eliminar duplicados.
- En rutas de tipo A, no sustituyas una persona, grupo, lugar, objeto o
  acontecimiento por otro sujeto relacionado, aunque sea de la misma época.
- En rutas de tipo A, la página de origen, la URL o el pie de foto debe
  permitir comprobar el sujeto principal; si no, descarta el resultado.
- En rutas de tipo B, la fuente debe acreditar el contexto central, el lugar
  o la época. No aceptes una estética parecida de otro movimiento o país.
- Solo admite personas anónimas cuando se pida expresamente público,
  multitud, vida cotidiana, moda, ambiente, calles o escena colectiva.
- Respeta lugar, fecha, época, encuadre y actividad solicitados.
- No devuelvas ilustraciones, carteles, pinturas, recreaciones, imágenes
  generadas por IA, fotogramas de ficción ni actores interpretando los
  hechos, salvo que la petición lo autorice expresamente.
- Prioriza material fotográfico original de archivos históricos,
  museos, bibliotecas, instituciones, Wikimedia Commons y medios fiables.
- Si no existen fotografías verificables, devuelve menos resultados.
- No rellenes con coincidencias aproximadas ni resultados genéricos.
""".strip()


def extraer_consultas_ejecutadas(elemento: dict) -> list[str]:
    accion = convertir_a_diccionario(elemento.get("action"))
    consultas = []

    consulta_unica = texto_seguro(
        accion.get("query")
    )

    if consulta_unica:
        consultas.append(consulta_unica)

    consultas_multiples = accion.get("queries", [])

    if isinstance(consultas_multiples, list):
        consultas.extend(
            texto_seguro(consulta)
            for consulta in consultas_multiples
            if texto_seguro(consulta)
        )

    return limpiar_consultas(consultas)


def extraer_resultados_imagen(respuesta: Any) -> list[dict]:
    resultados = []
    elementos_salida = getattr(respuesta, "output", None) or []

    for elemento in elementos_salida:
        datos_elemento = convertir_a_diccionario(elemento)

        if datos_elemento.get("type") != "web_search_call":
            continue

        consultas_web = extraer_consultas_ejecutadas(
            datos_elemento
        )

        resultados_elemento = datos_elemento.get("results") or []

        if not isinstance(resultados_elemento, (list, tuple)):
            continue

        for resultado in resultados_elemento:
            datos_resultado = convertir_a_diccionario(resultado)

            if datos_resultado.get("type") != "image_result":
                continue

            imagen_url = texto_seguro(
                datos_resultado.get("image_url")
            )
            fuente_url = texto_seguro(
                datos_resultado.get("source_website_url")
            )

            if not imagen_url or not fuente_url:
                continue

            miniatura_url = texto_seguro(
                datos_resultado.get("thumbnail_url")
            ) or imagen_url
            descripcion = texto_seguro(
                datos_resultado.get("caption")
            )
            titulo = texto_seguro(datos_resultado.get("title"))
            autor = texto_seguro(datos_resultado.get("author"))
            fuente_nombre = texto_seguro(
                datos_resultado.get("source_name")
            )
            resultados.append(
                {
                    "imagen_url": imagen_url,
                    "miniatura_url": miniatura_url,
                    "fuente_url": fuente_url,
                    "descripcion": descripcion,
                    "titulo": titulo,
                    "autor": autor,
                    "fuente_nombre": fuente_nombre,
                    "_consultas_web": consultas_web,
                }
            )

    return resultados


def es_url_web(url: str) -> bool:
    try:
        datos = urlparse(texto_seguro(url))
    except ValueError:
        return False

    return datos.scheme in {"http", "https"} and bool(datos.netloc)


def obtener_dominio(url: str) -> str:
    try:
        dominio = urlparse(texto_seguro(url)).netloc.casefold()
    except ValueError:
        return ""

    return dominio.removeprefix("www.")


def tokenizar_en_orden(texto: str) -> list[str]:
    palabras = re.findall(
        r"[a-z0-9]+",
        normalizar_texto(texto),
    )
    resultado = []
    vistas = set()

    for palabra in palabras:
        if palabra in PALABRAS_VACIAS:
            continue

        if len(palabra) < 3 and not palabra.isdigit():
            continue

        if palabra in vistas:
            continue

        vistas.add(palabra)
        resultado.append(palabra)

    return resultado


def obtener_tokens(texto: str) -> set[str]:
    return set(tokenizar_en_orden(texto))


def extraer_frases_importantes(
    consultas: list[str],
) -> list[str]:
    frases = []

    for consulta in consultas:
        candidatas = []
        candidatas.extend(
            re.findall(
                r"[\"“”'‘’]([^\"“”'‘’]{2,80})[\"“”'‘’]",
                consulta,
            )
        )
        candidatas.extend(
            re.findall(
                r"\b[\wÀ-ÿ0-9]+(?:[-–—][\wÀ-ÿ0-9]+)+\b",
                consulta,
            )
        )
        candidatas.extend(
            re.findall(
                r"\b[A-ZÁÉÍÓÚÜÑ][\wÀ-ÿ'’-]{2,}"
                r"(?:\s+(?:de\s+|del\s+|la\s+|los\s+)?"
                r"[A-ZÁÉÍÓÚÜÑ][\wÀ-ÿ'’-]{2,}){0,3}",
                consulta,
            )
        )

        for candidata in candidatas:
            tokens = tokenizar_en_orden(candidata)

            if not tokens:
                continue

            frase = " ".join(tokens)

            if frase not in frases:
                frases.append(frase)

    return frases


def obtener_tokens_nucleo(
    consultas: list[str],
) -> set[str]:
    conjuntos = [
        obtener_tokens(consulta)
        for consulta in consultas
        if obtener_tokens(consulta)
    ]

    if not conjuntos:
        return set()

    if len(conjuntos) == 1:
        frases = extraer_frases_importantes(consultas)

        if frases:
            return set().union(
                *(obtener_tokens(frase) for frase in frases)
            )

        return set(tokenizar_en_orden(consultas[0])[:3])

    frecuencias = Counter(
        token
        for conjunto in conjuntos
        for token in conjunto
    )
    minimo_apariciones = max(2, (len(conjuntos) + 1) // 2)
    nucleo = {
        token
        for token, frecuencia in frecuencias.items()
        if frecuencia >= minimo_apariciones
    }

    if nucleo:
        return nucleo

    frases = extraer_frases_importantes(consultas)

    if frases:
        return set().union(
            *(obtener_tokens(frase) for frase in frases)
        )

    return set(tokenizar_en_orden(consultas[0])[:3])


def extraer_grupos_identidad(
    consultas: list[str],
) -> list[set[str]]:
    """Extrae nombres distintivos sin confundirlos con la escena."""
    grupos_con_prioridad: list[tuple[int, set[str]]] = []

    for consulta in consultas:
        candidatas_por_tipo = [
            (
                3,
                re.findall(
                    r"[\"\u201c\u201d'\u2018\u2019]([^\"\u201c\u201d'\u2018\u2019]{2,80})"
                    r"[\"\u201c\u201d'\u2018\u2019]",
                    consulta,
                ),
            ),
            (
                3,
                re.findall(
                    r"\b[\wÀ-ÿ0-9]+(?:[-–—][\wÀ-ÿ0-9]+)+\b",
                    consulta,
                ),
            ),
            (
                2,
                re.findall(
                    r"\b[A-ZÁÉÍÓÚÜÑ][\wÀ-ÿ'’-]{2,}"
                    r"(?:\s+(?:de\s+|del\s+|la\s+|los\s+)?"
                    r"[A-ZÁÉÍÓÚÜÑ][\wÀ-ÿ'’-]{2,}){0,3}",
                    consulta,
                ),
            ),
        ]

        for prioridad, candidatas in candidatas_por_tipo:
            for candidata in candidatas:
                tokens_ordenados = [
                    token
                    for token in tokenizar_en_orden(candidata)
                    if token not in PALABRAS_GENERICAS_IDENTIDAD
                ]

                if not tokens_ordenados:
                    continue

                if prioridad == 2 and len(tokens_ordenados) >= 3:
                    for indice in range(len(tokens_ordenados) - 1):
                        grupos_con_prioridad.append(
                            (
                                prioridad,
                                set(tokens_ordenados[indice:indice + 2]),
                            )
                        )
                else:
                    grupos_con_prioridad.append(
                        (prioridad, set(tokens_ordenados))
                    )

    if not grupos_con_prioridad:
        return []

    grupos_fuertes = [
        grupo
        for prioridad, grupo in grupos_con_prioridad
        if prioridad >= 3
    ]
    grupos_nombres = [
        grupo
        for prioridad, grupo in grupos_con_prioridad
        if prioridad == 2 and len(grupo) >= 2
    ]

    if grupos_fuertes:
        grupos_nombres = [
            grupo
            for grupo in grupos_nombres
            if all(
                not (grupo & fuerte) or fuerte <= grupo
                for fuerte in grupos_fuertes
            )
        ]

    if grupos_fuertes or grupos_nombres:
        grupos = grupos_fuertes + grupos_nombres
    else:
        grupos = [
            grupo
            for _, grupo in grupos_con_prioridad
        ]

    grupos = [
        grupo
        for indice, grupo in enumerate(grupos)
        if grupo not in grupos[:indice]
    ]

    grupos_minimos = []

    for grupo in sorted(grupos, key=len):
        if any(existente <= grupo for existente in grupos_minimos):
            continue

        grupos_minimos.append(grupo)

    return grupos_minimos


def es_consulta_contextual(consulta: str) -> bool:
    texto_normalizado = normalizar_texto(consulta)
    tokens = obtener_tokens(texto_normalizado)
    indicios_contextuales = (
        tokens & INDICIOS_OBJETIVO_CONTEXTUAL
    )
    indicios_exactos = tokens & INDICIOS_SUJETO_EXACTO

    if indicios_exactos and extraer_grupos_identidad([consulta]):
        return False

    if len(indicios_contextuales) >= 2:
        return True

    return not extraer_grupos_identidad([consulta])


def coincidencia_contextual(
    candidata: dict,
    consulta: str,
) -> bool:
    tokens_consulta = obtener_tokens(consulta)
    tokens_metadatos = obtener_tokens(
        obtener_metadatos(candidata)
    )

    if not tokens_consulta or not tokens_metadatos:
        return False

    coincidencias = tokens_consulta & tokens_metadatos
    if len(coincidencias) < 2:
        return False

    anclas = {
        token
        for token in tokens_consulta
        if token not in INDICIOS_OBJETIVO_CONTEXTUAL
        and token not in PALABRAS_GENERICAS_IDENTIDAD
        and not token.isdigit()
    }

    if anclas:
        return bool(anclas & tokens_metadatos)

    return True


def coincidencia_consulta_individual(
    candidata: dict,
    consulta: str,
) -> bool:
    if es_consulta_contextual(consulta):
        return coincidencia_contextual(candidata, consulta)

    tokens_metadatos = obtener_tokens(
        obtener_metadatos(candidata)
    )
    grupos_identidad = extraer_grupos_identidad([consulta])

    if grupos_identidad:
        return any(
            grupo <= tokens_metadatos
            for grupo in grupos_identidad
        )

    return coincidencia_contextual(candidata, consulta)


def obtener_metadatos(candidata: dict) -> str:
    return " ".join(
        parte
        for parte in [
            texto_seguro(candidata.get("titulo")),
            texto_seguro(candidata.get("autor")),
            texto_seguro(candidata.get("descripcion")),
            texto_seguro(candidata.get("fuente_nombre")),
            texto_seguro(candidata.get("fuente_url")),
            texto_seguro(candidata.get("imagen_url")),
        ]
        if parte
    )


def contiene_material_no_documental(candidata: dict) -> bool:
    metadatos = normalizar_texto(
        obtener_metadatos(candidata)
    )

    return any(
        indicio in metadatos
        for indicio in INDICIOS_NO_DOCUMENTALES
    )


def obtener_consultas_relevancia(
    candidata: dict,
    consultas: list[str],
) -> list[str]:
    # Las consultas creadas por el buscador ayudan a encontrar imágenes,
    # pero nunca deben rebajar el criterio original de validación.
    return limpiar_consultas(consultas)


def puntuacion_consulta(
    candidata: dict,
    consulta: str,
) -> int:
    tokens_consulta = obtener_tokens(consulta)

    if not tokens_consulta:
        return 0

    tokens_metadatos = obtener_tokens(
        obtener_metadatos(candidata)
    )

    return len(tokens_consulta & tokens_metadatos)


def coincidencia_suficiente(
    candidata: dict,
    consultas: list[str],
) -> bool:
    consultas_relevancia = obtener_consultas_relevancia(
        candidata,
        consultas,
    )

    return any(
        coincidencia_consulta_individual(candidata, consulta)
        for consulta in consultas_relevancia
    )


def dominio_documental(dominio: str) -> bool:
    return any(
        dominio == permitido
        or dominio.endswith(f".{permitido}")
        for permitido in DOMINIOS_DOCUMENTALES
    )


def puntuar_candidata(
    candidata: dict,
    consultas: list[str],
) -> int:
    consultas_relevancia = obtener_consultas_relevancia(
        candidata,
        consultas,
    )
    metadatos = obtener_metadatos(candidata)
    metadatos_normalizados = normalizar_texto(metadatos)
    tokens_metadatos = obtener_tokens(metadatos)
    tokens_nucleo = obtener_tokens_nucleo(
        consultas_relevancia
    )
    frases = extraer_frases_importantes(
        consultas_relevancia
    )
    puntuacion = 0

    puntuacion += 5 * len(tokens_nucleo & tokens_metadatos)

    for frase in frases:
        if frase and frase in metadatos_normalizados:
            puntuacion += 12

    coincidencias_por_consulta = [
        puntuacion_consulta(candidata, consulta)
        for consulta in consultas_relevancia
    ]

    if coincidencias_por_consulta:
        puntuacion += 3 * max(coincidencias_por_consulta)
        puntuacion += sum(
            1
            for coincidencias in coincidencias_por_consulta
            if coincidencias >= 2
        )

    if texto_seguro(candidata.get("descripcion")):
        puntuacion += 2

    if dominio_documental(
        obtener_dominio(candidata.get("fuente_url", ""))
    ):
        puntuacion += 4

    return puntuacion


def validar_candidatas_localmente(
    candidatas: list[dict],
    consultas: list[str],
) -> list[dict]:
    validas = []

    for candidata in candidatas:
        if not es_url_web(candidata.get("imagen_url", "")):
            continue

        if not es_url_web(candidata.get("fuente_url", "")):
            continue

        if contiene_material_no_documental(candidata):
            continue

        if not coincidencia_suficiente(candidata, consultas):
            continue

        candidata_validada = dict(candidata)
        candidata_validada["_puntuacion"] = puntuar_candidata(
            candidata,
            consultas,
        )
        validas.append(candidata_validada)

    return sorted(
        validas,
        key=lambda candidata: candidata.get("_puntuacion", 0),
        reverse=True,
    )


def eliminar_duplicados(candidatas: list[dict]) -> list[dict]:
    candidatas_unicas = []
    urls_vistas = set()
    metadatos_vistos = set()

    for candidata in candidatas:
        imagen_url = texto_seguro(candidata.get("imagen_url"))
        miniatura_url = texto_seguro(
            candidata.get("miniatura_url")
        )
        fuente_url = texto_seguro(candidata.get("fuente_url"))
        descripcion = normalizar_texto(
            candidata.get("descripcion", "")
        )
        clave_metadatos = (
            fuente_url.casefold(),
            descripcion,
        )

        if not imagen_url or imagen_url in urls_vistas:
            continue

        if miniatura_url and miniatura_url in urls_vistas:
            continue

        if (
            all(clave_metadatos)
            and clave_metadatos in metadatos_vistos
        ):
            continue

        urls_vistas.add(imagen_url)

        if miniatura_url:
            urls_vistas.add(miniatura_url)

        if all(clave_metadatos):
            metadatos_vistos.add(clave_metadatos)

        candidatas_unicas.append(candidata)

    return candidatas_unicas


def buscar_en_una_respuesta(
    consultas: list[str],
    max_resultados: int,
) -> list[dict]:
    cliente = obtener_cliente()
    resultados_por_busqueda = max(
        max_resultados,
        MAXIMO_RESULTADOS_POR_BUSQUEDA,
    )
    respuesta = cliente.responses.create(
        model=MODELO_BUSQUEDA,
        reasoning={"effort": "low"},
        tools=[
            {
                "type": "web_search",
                "search_content_types": [
                    "image",
                    "text",
                ],
                "image_settings": {
                    "max_results": resultados_por_busqueda,
                    "caption": True,
                },
            }
        ],
        tool_choice="required",
        max_tool_calls=MAXIMO_LLAMADAS_WEB,
        max_output_tokens=256,
        include=["web_search_call.results"],
        store=False,
        input=crear_prompt_busqueda(
            consultas,
            max_resultados,
        ),
    )

    return extraer_resultados_imagen(respuesta)


def preparar_salida(candidata: dict) -> dict:
    fuente_url = texto_seguro(candidata.get("fuente_url"))
    fuente_nombre = (
        texto_seguro(candidata.get("fuente_nombre"))
        or obtener_dominio(fuente_url)
        or "Fuente sin identificar"
    )
    descripcion_original = texto_seguro(
        candidata.get("descripcion")
    )
    titulo_original = texto_seguro(candidata.get("titulo"))
    autor = texto_seguro(candidata.get("autor"))

    if descripcion_original:
        descripcion = descripcion_original
        titulo = titulo_original or descripcion_original
    else:
        titulo = (
            titulo_original
            or f"Fotografía candidata de {fuente_nombre}"
        )
        descripcion = (
            "Sin descripción disponible en el resultado. "
            f"Fuente: {fuente_nombre}. Verifica la página de origen."
        )

    return {
        "imagen_url": texto_seguro(candidata.get("imagen_url")),
        "miniatura_url": (
            texto_seguro(candidata.get("miniatura_url"))
            or texto_seguro(candidata.get("imagen_url"))
        ),
        "fuente_url": fuente_url,
        "fuente_nombre": fuente_nombre,
        "titulo": titulo,
        "autor": autor,
        "descripcion": descripcion,
    }


def buscar_imagenes_reales(
    busquedas: list[str],
    max_resultados: int = 6,
) -> list[dict]:
    consultas = limpiar_consultas(busquedas)

    if not consultas:
        raise ValueError(
            "No existen búsquedas para localizar fotografías reales."
        )

    max_resultados = max(
        1,
        min(max_resultados, MAXIMO_RESULTADOS),
    )

    if obtener_modo_busqueda() == MODO_PRUEBA:
        return crear_resultado_prueba(consultas[0])

    candidatas = buscar_en_una_respuesta(
        consultas,
        max_resultados,
    )
    candidatas = eliminar_duplicados(candidatas)
    candidatas = validar_candidatas_localmente(
        candidatas,
        consultas,
    )[:max_resultados]

    if not candidatas:
        raise ValueError(
            "La búsqueda no encontró fotografías verificables para "
            "ninguna de las rutas solicitadas. No se devolverán "
            "coincidencias aproximadas."
        )

    return [
        preparar_salida(candidata)
        for candidata in candidatas
    ]
